[variables]
PYTHON_VERSION = "3.11"
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_18", "npm"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "npm install"
]

[phases.start]
cmd = "python app.py"