-- Supabase-ready PostgreSQL schema generated from SQLite (replicates tables & fields)

CREATE TABLE IF NOT EXISTS "sitreps" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "source" TEXT NOT NULL,
    "title" TEXT,
    "description" TEXT,
    "severity" TEXT,
    "lat" DOUBLE PRECISION NOT NULL,
    "lon" DOUBLE PRECISION NOT NULL,
    "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
    "source_category" TEXT,
    "status" TEXT,
    "unit" TEXT,
    "contact" TEXT,
    "incident_type" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "chatbot_conversations" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "session_id" TEXT,
    "user_message" TEXT,
    "bot_response" TEXT,
    "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "context_data" TEXT,
    PRIMARY KEY ("id")
);

-- Row Level Security Policies
-- Enable RLS on tables
ALTER TABLE "sitreps" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "chatbot_conversations" ENABLE ROW LEVEL SECURITY;

-- Policies for sitreps table
-- Allow public read access (for your application to query data)
CREATE POLICY "Allow public read access on sitreps" ON "sitreps"
    FOR SELECT USING (true);

-- Allow public insert access (for creating new sitreps)
CREATE POLICY "Allow public insert access on sitreps" ON "sitreps"
    FOR INSERT WITH CHECK (true);

-- Allow public update access (for updating sitreps)
CREATE POLICY "Allow public update access on sitreps" ON "sitreps"
    FOR UPDATE USING (true);

-- Allow public delete access (for deleting sitreps)
CREATE POLICY "Allow public delete access on sitreps" ON "sitreps"
    FOR DELETE USING (true);

-- Policies for chatbot_conversations table
-- Allow public read access
CREATE POLICY "Allow public read access on chatbot_conversations" ON "chatbot_conversations"
    FOR SELECT USING (true);

-- Allow public insert access
CREATE POLICY "Allow public insert access on chatbot_conversations" ON "chatbot_conversations"
    FOR INSERT WITH CHECK (true);

-- Allow public update access
CREATE POLICY "Allow public update access on chatbot_conversations" ON "chatbot_conversations"
    FOR UPDATE USING (true);

-- Allow public delete access
CREATE POLICY "Allow public delete access on chatbot_conversations" ON "chatbot_conversations"
    FOR DELETE USING (true);
